// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace LiBackgammon.Migrations
{
    [DbContext(typeof(Db))]
    partial class DbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LiBackgammon.ChatMessage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GameID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Player")
                        .HasColumnType("int");

                    b.Property<bool>("Seen")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("LiBackgammon.Game", b =>
                {
                    b.Property<string>("PublicID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BlackScore")
                        .HasColumnType("int");

                    b.Property<string>("BlackToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GameInMatch")
                        .HasColumnType("int");

                    b.Property<bool>("HasDoublingCube")
                        .HasColumnType("bit");

                    b.Property<string>("InitialPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Match")
                        .HasColumnType("int");

                    b.Property<string>("Moves")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NextGame")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RematchOffer")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.Property<int>("WhiteScore")
                        .HasColumnType("int");

                    b.Property<string>("WhiteToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PublicID");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("LiBackgammon.Language", b =>
                {
                    b.Property<string>("HashName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HashName");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("LiBackgammon.Match", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DoublingCubeRules")
                        .HasColumnType("int");

                    b.Property<string>("FirstGame")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("LiBackgammon.Style", b =>
                {
                    b.Property<string>("HashName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<string>("Css")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HashName");

                    b.ToTable("Styles");
                });

            modelBuilder.Entity("LiBackgammon.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int>("Flags")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LiBackgammon.UserSession", b =>
                {
                    b.Property<string>("SessionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("SessionID");

                    b.ToTable("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
